-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 21:35:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema selectCourse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema selectCourse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `selectCourse` DEFAULT CHARACTER SET utf8 ;
USE `selectCourse` ;

-- -----------------------------------------------------
-- Table `selectCourse`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`department` (
  `dept_name` VARCHAR(45) NOT NULL,
  `telephone` CHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `building` VARCHAR(45) NULL,
  `description` VARCHAR(5000) NULL,
  PRIMARY KEY (`dept_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`users` (
  `user_id` CHAR(11) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`student` (
  `sutdent_id` CHAR(11) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `entrance_year` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sutdent_id`),
  INDEX `dept_name_idx` (`dept_name` ASC) VISIBLE,
  CONSTRAINT `student_dept`
    FOREIGN KEY (`dept_name`)
    REFERENCES `selectCourse`.`department` (`dept_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_user`
    FOREIGN KEY (`sutdent_id`)
    REFERENCES `selectCourse`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`course` (
  `course_id` CHAR(11) NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `dept_name` VARCHAR(45) NULL,
  `credit` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `dept_name_idx` (`dept_name` ASC) VISIBLE,
  CONSTRAINT `course_dept`
    FOREIGN KEY (`dept_name`)
    REFERENCES `selectCourse`.`department` (`dept_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `selectCourse`.`classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`classroom` (
  `classroom_id` CHAR(11) NOT NULL,
  `building` VARCHAR(45) NULL,
  ` capacity` INT NOT NULL,
  `room_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classroom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`section` (
  `section_id` CHAR(11) NOT NULL,
  `max_students` INT NOT NULL,
  `class_times` INT NOT NULL COMMENT '上多少周课',
  `year` CHAR(4) NOT NULL COMMENT '开课年份\n',
  `evaluation_mode` CHAR(1) NOT NULL COMMENT '考核方式',
  `semester` VARCHAR(45) NOT NULL COMMENT '秋季学期还是春季',
  PRIMARY KEY (`section_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`time_slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`time_slot` (
  `time_slot_id` CHAR(11) NOT NULL,
  `day` CHAR(1) NOT NULL COMMENT '星期几',
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  PRIMARY KEY (`time_slot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`examination` (
  `exam_id` CHAR(11) NOT NULL,
  `date` DATE NOT NULL,
  `modality` VARCHAR(45) NOT NULL,
  `instructor_id` CHAR(11) NOT NULL,
  `classroom_id` CHAR(11) NOT NULL,
  `exam_start` TIME NOT NULL,
  `exam_end` TIME NOT NULL,
  PRIMARY KEY (`exam_id`),
  INDEX `classroom_id_idx` (`classroom_id` ASC) VISIBLE,
  CONSTRAINT `classroom_examination`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `selectCourse`.`classroom` (`classroom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`inst_dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`inst_dept` (
  `dept_name` VARCHAR(20) NOT NULL,
  `instructor_id` CHAR(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`stud_dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`stud_dept` (
  `dept_name` VARCHAR(20) NOT NULL,
  `student_id` CHAR(11) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`takes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`takes` (
  `student_id` CHAR(11) NOT NULL,
  `section_id` CHAR(11) NOT NULL,
  `grade` CHAR(2) NULL,
  `state` VARCHAR(45) NULL,
  `application` VARCHAR(300) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`course_dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`course_dept` (
  `cousre_id` CHAR(11) NOT NULL,
  `dept_name` VARCHAR(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`sec_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`sec_course` (
  `course_id` CHAR(11) NOT NULL,
  `section_id` CHAR(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`sec_classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`sec_classroom` (
  `classroom_id` CHAR(11) NOT NULL,
  `section_id` CHAR(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`sec_time_slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`sec_time_slot` (
  `time_slot_id` CHAR(11) NOT NULL,
  `section_id` CHAR(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`teaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`teaches` (
  `instructor_id` CHAR(11) NOT NULL,
  `cousre_id` CHAR(11) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`sec_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`sec_exam` (
  `exam_id` CHAR(11) NOT NULL,
  `section_id` CHAR(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`instructor` (
  `instructor_id` CHAR(11) NOT NULL,
  `inst_name` VARCHAR(45) NOT NULL,
  `dept_name` VARCHAR(45) NOT NULL,
  `payment` FLOAT NULL,
  PRIMARY KEY (`instructor_id`),
  INDEX `dept_name_idx` (`dept_name` ASC) VISIBLE,
  CONSTRAINT `inst_dept`
    FOREIGN KEY (`dept_name`)
    REFERENCES `selectCourse`.`department` (`dept_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inst_user`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `selectCourse`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selectCourse`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selectCourse`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
